### ISSUE TITLE
Pass new message as argument

### ISSUE THREAD

**Issue by renatosilva** [tymm/command-execute#1]
I suggest allowing to pass the message as argument using some placeholder like $message or something. That's because I wanted to use bash to echo the text to a temp file then pass that temp file path to another program.

**Comment by tymm** [comment]
That really would be nice to have.
I will try to add this feature when i have some spare time and enough motivation.

**Comment by renatosilva** [comment]
Thanks. I plan to use a text-to-speech program for speaking what people say in some chats!

**Comment by tymm** [comment]
Cool. Did you check other notification plugins for that feature? Maybe someone already did this.

**Comment by renatosilva** [comment]
Yes, but it seems yours is the closest. I suggested it because it may be simple to implement yet useful for other situations.

**Comment by tymm** [comment]
Check out the develop branch for this feature. It's still super buggy/unsecure and I probably will have no time soon to complete it but it should work more or less already.

**Comment by juliohm1978** [comment]
+1 for that. With that feature, it would be easy to create a script that displays a popup on the desktop that selectively shows the content of the message based on a whitelist/blacklist. This is itneresting if you use pidgin in the workplace and have multiple accounts setup (personal, work, others). IMs from coworkers are always welcome, but sometimes you get a private message from your family and would like its contents to be hidden from your monitor.

**Comment by zalman** [comment]
Hi, @tymm, do you still support that project? I can motivate you the more there is a solution that implemetns that feature

**Comment by tymm** [comment]
@zalman sorry, I don't have time anymore to support this project.
