### ISSUE TITLE
Execute command from selected text

### ISSUE THREAD

**Issue by renatosilva** [tymm/command-execute#2]
It would be nice if I could select a text, right click and select a command to execute from the context menu. The command would receive the selected text as argument according to the configured command call. The plug-in would allow to register several commands to be executed from a selected text's context menu.

For example:
Label: "Translate to Portuguese"
Command-line: "firefox www.wordreference.com/enpt/$selection"

Then I would select a text in a conversation, right click, pick translate option and have the webpage opened.

**Comment by tymm** [comment]
Sorry, since I wrote this plugin to have command execution working for pidgin _and_ finch this is not really doable without a lot of work.
Selecting text in finch and passing it to the plugin probably requires a lot of hacking and is certainly not supported by the API.

**Comment by renatosilva** [comment]
Ok, it would be nice if they had some UI abstraction layer. I think I would need to write a Pidgin plug-in myself. Thanks anyway.

**Comment by tymm** [comment]
Good luck. It shouldn't be too hard to write something like this for pidgin only.
