### ISSUE TITLE
execute command on chat room activity

### ISSUE THREAD

**Issue by crovaxon** [tymm/command-execute#4]
Hello!

I am looking for a way to make pidgin turn off my screensaver on a message and your plugin works perfectly for this, except with chat rooms.
Would it be possible to have the plugin also react on chat room activity?

**Comment by tymm** [comment]
Hey.

I just added this feature for you.
Would be nice if you could let me know if it is working because I'm too busy for testing it right now.

**Comment by crovaxon** [comment]
Awesome, thank you very much!
Works just how I wanted it to work and without a problem so far. I let it execute a command that turns off the screensaver, which immediately gets my attention when I sit at the desk.

Thanks again!
