### ISSUE TITLE
Windows dll

### ISSUE THREAD

**Issue by CP1832** [tymm/command-execute#5]
I'm not sure this is an issue, but in case this plugin works in Windows, would it be possible for you / anyone to upload the dll file?

Thanks in advance.

**Comment by tymm** [comment]
Hey.

You are totally right. It would be nice to have a .dll version of the plugin.
I tried to cross-compile it to Windows from my Linux machine for the last few hours but didn't succeed.

I can compile it but linking fails for some reason.
I will look into it again when I have some more time.

If someone else is able to get a working .dll out of the source code, I will be thankful for a pull request.
